### ISSUE TITLE
Clean Stale Issues, generate milestones, and address current valid pull requests

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1388]
Need to get the issues for this project cleaned up so that we can efficiently communicate progress.

- [x] acknowledge all outstanding issues
- [ ] close out all issues older than 6 months with a note to reopen if still necessary
- [ ] review each issue and check for validity, feasibility, and area
        - accept or reject issues (accepted issues go to "ready" status, others "rejected" status)
        - tag all accepted issues with "area" tag
- [ ] investigate ready issues and determine if it is necessary to get responsible team to help
        - tag issues with "needs help" where necessary
